[2022-12-04 16:35:45,338] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: data_ingest_yuda.call_dataset_task manual__2022-12-04T16:35:44.032351+00:00 [queued]>
[2022-12-04 16:35:45,347] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: data_ingest_yuda.call_dataset_task manual__2022-12-04T16:35:44.032351+00:00 [queued]>
[2022-12-04 16:35:45,348] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-12-04 16:35:45,349] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2022-12-04 16:35:45,349] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-12-04 16:35:45,362] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): call_dataset_task> on 2022-12-04 16:35:44.032351+00:00
[2022-12-04 16:35:45,366] {standard_task_runner.py:52} INFO - Started process 1634 to run task
[2022-12-04 16:35:45,372] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'data_ingest_yuda', 'call_dataset_task', 'manual__2022-12-04T16:35:44.032351+00:00', '--job-id', '13', '--raw', '--subdir', 'DAGS_FOLDER/data_ingest_yuda.py', '--cfg-path', '/tmp/tmpjmyccivg', '--error-file', '/tmp/tmpp6nduglu']
[2022-12-04 16:35:45,374] {standard_task_runner.py:77} INFO - Job 13: Subtask call_dataset_task
[2022-12-04 16:35:45,427] {logging_mixin.py:109} INFO - Running <TaskInstance: data_ingest_yuda.call_dataset_task manual__2022-12-04T16:35:44.032351+00:00 [running]> on host 73a87de6132e
[2022-12-04 16:35:45,479] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=yudasatrias
AIRFLOW_CTX_DAG_ID=data_ingest_yuda
AIRFLOW_CTX_TASK_ID=call_dataset_task
AIRFLOW_CTX_EXECUTION_DATE=2022-12-04T16:35:44.032351+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-12-04T16:35:44.032351+00:00
[2022-12-04 16:35:45,920] {python.py:175} INFO - Done. Returned value was: None
[2022-12-04 16:35:45,934] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=data_ingest_yuda, task_id=call_dataset_task, execution_date=20221204T163544, start_date=20221204T163545, end_date=20221204T163545
[2022-12-04 16:35:45,987] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-12-04 16:35:46,031] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
