[2022-12-04 16:23:41,016] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: data_ingest_yuda.save_as_csv_task scheduled__2022-12-03T00:00:00+00:00 [queued]>
[2022-12-04 16:23:41,027] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: data_ingest_yuda.save_as_csv_task scheduled__2022-12-03T00:00:00+00:00 [queued]>
[2022-12-04 16:23:41,029] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-12-04 16:23:41,030] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2022-12-04 16:23:41,030] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-12-04 16:23:41,041] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): save_as_csv_task> on 2022-12-03 00:00:00+00:00
[2022-12-04 16:23:41,047] {standard_task_runner.py:52} INFO - Started process 1029 to run task
[2022-12-04 16:23:41,050] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'data_ingest_yuda', 'save_as_csv_task', 'scheduled__2022-12-03T00:00:00+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/data_ingest_yuda.py', '--cfg-path', '/tmp/tmpsq1_vkb0', '--error-file', '/tmp/tmpmbyo9nyq']
[2022-12-04 16:23:41,051] {standard_task_runner.py:77} INFO - Job 4: Subtask save_as_csv_task
[2022-12-04 16:23:41,209] {logging_mixin.py:109} INFO - Running <TaskInstance: data_ingest_yuda.save_as_csv_task scheduled__2022-12-03T00:00:00+00:00 [running]> on host 73a87de6132e
[2022-12-04 16:23:41,413] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=yudasatrias
AIRFLOW_CTX_DAG_ID=data_ingest_yuda
AIRFLOW_CTX_TASK_ID=save_as_csv_task
AIRFLOW_CTX_EXECUTION_DATE=2022-12-03T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-12-03T00:00:00+00:00
[2022-12-04 16:23:41,483] {python.py:175} INFO - Done. Returned value was: None
[2022-12-04 16:23:41,501] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=data_ingest_yuda, task_id=save_as_csv_task, execution_date=20221203T000000, start_date=20221204T162341, end_date=20221204T162341
[2022-12-04 16:23:41,585] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-12-04 16:23:41,620] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
